# numpy
* [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)
* numpy: Numerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬 list와의 차이는 자료형이 1가지만 들어간다.
* 우선순위 int < float < str

# 차원
* 0 차원 = 점 . 스칼라  a = 10
* 1 차원 = 선 --- 방향이 없는 벡터, 배열, list, tuple  [1,2,3,4]
* 2 차원 = 면 가로, 세로, DB 테이블, DataFrame, excel Sheet, matrix, 행렬
* 3 차원 = 입체, 가로, 세로, 깊이, 정육면체(주사위), 2차원 데이터의 묶음, excel file
* 4 차원 = 3차원 데이터의 묶음
* 5 차원 = 4차원 데이터의 묶음


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
num = 10

* 차원을 출력하는 메서드 .ndim
* 차원의 형태를 출력하는 메서드 .shape

In [4]:
num.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [6]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [7]:
# ndarray는 방향이 없는 벡터
a.shape

(5,)

In [8]:
# 세로로 방향을 가진 열벡터
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
a2.shape

(5, 1)

In [10]:
a2.ndim

2

In [11]:
# 행이 1개고 열이 여러개인 행벡터
a3 = np.array([[1,2,3,4,5]])
a3

array([[1, 2, 3, 4, 5]])

In [12]:
a3.ndim

2

In [13]:
a3.shape

(1, 5)

# 2차원 데이터

In [14]:
d2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
print(d2.ndim, d2.shape)

2 (2, 5)


# 3차원 데이터

In [18]:
d3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]])
d3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [24]:
print(d3.ndim, d3.shape)

3 (4, 2, 5)


# 4차원 데이터

In [19]:
d4 = np.array([[[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]],
              [[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]]])
d4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [23]:
print(d4.ndim, d4.shape)

4 (2, 4, 2, 5)


# 5차원 데이터

In [20]:
d5 = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]],
              [[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]]],
              [[[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]],
              [[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]]]])
d5

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

  

In [25]:
print(d5.ndim, d5.shape)

5 (2, 2, 4, 2, 5)


In [26]:
l5 = [[[[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]],
              [[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]]],
              [[[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]],
              [[[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]],
             [[1,2,3,4,5],[6,7,8,9,10]], [[1,2,3,4,5],[6,7,8,9,10]]]]]
l5

[[[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]],
  [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]]],
 [[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]],
  [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]]]]

# 넘파이를 사용해야 하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [27]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
scalar

15

In [28]:
scalar + 10

25

In [30]:
# 1차원 벡터의 연산
v1 = [1,2,3,4,5]

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [31]:
# v1의 요소에 10을 곱한 리스트로 만드세요.
mul10 = []
for num in v1:
    mul10.append(num * 10)
mul10

[10, 20, 30, 40, 50]

In [32]:
mul10 = [num * 10 for num in v1]
mul10

[10, 20, 30, 40, 50]

In [37]:
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
# 2차원 데이터 연산 10 곱해서 출력
result = []
for l1 in d2:
    temp = []
    for num in l1:
        temp.append(num * 10)
    result.append(temp)
result

[[np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)], [np.int64(60), np.int64(70), np.int64(80), np.int64(90), np.int64(100)]]


In [41]:
# 3차원 데이터에 10 곱하는 연산

In [47]:
d3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [52]:
result3 = []
for item1 in d3:
    temp2 = []
    for item2 in item1:
        temp1 = []
        for item3 in item2:
            temp1.append(item3 * 10)
        temp2.append(temp1)
    result3.append(temp2)
result3 = np.array(result3)
print(result3,"\n",result3.ndim, result3.shape)

[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 10  20  30  40  50]
  [ 60  70  80  90 100]]] 
 3 (4, 2, 5)


In [58]:
# 4차원 데이터 연산 numpy
d4 * 10

array([[[[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]]],


       [[[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]],

        [[0.1, 0.2, 0.3, 0.4, 0.5],
         [0.6, 0.7, 0.8, 0.9, 1. ]]]])

# numpy에서 자주 사용하는 메서드
* .ndim : 몇 차원이지 확인
* .shpae : 몇 차원, 몇행, 몇열인지 구조 확인
* .size : 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype : 데이터 타입이 무엇인지

In [59]:
d5

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

  

In [60]:
print(d5.ndim, d5.shape, d5.size, d5.dtype)

5 (2, 2, 4, 2, 5) 160 int64


# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [61]:
e1 = np.array([1,2,3,4,5])
e1

array([1, 2, 3, 4, 5])

In [62]:
e2 = np.array((1,2,3,4,5))
e2

array([1, 2, 3, 4, 5])

In [64]:
e3 = np.array((1, 2, 3.0, 4, 5))
print(e3, e3.dtype)

[1. 2. 3. 4. 5.] float64


In [65]:
e4 = np.array((1, 2, 3.0, "4", 5))
print(e4, e4.dtype)

['1' '2' '3.0' '4' '5'] <U32


# np.arange(시작, 끝, step)

In [67]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [68]:
a2 = np.arange(11, 1, -3)
a2

array([11,  8,  5,  2])

In [69]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# .reshape(행, 열)
* 벡터를 원하는 크기의 다차원 배열로 변환

In [70]:
print(a3.ndim, a3.shape)

1 (100,)


In [72]:
a4 = a3.reshape(20, 5)
print(a4.ndim, a4.shape)
a4

2 (20, 5)


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [73]:
a4 = a3.reshape(5, 2, 2, 5)
print(a4.ndim, a4.shape)

4 (5, 2, 2, 5)


In [83]:
a5 = a3.reshape(-1, 1, 2, 2, 5)
print(a5.ndim, a5.shape)

5 (5, 1, 2, 2, 5)


In [76]:
a5

array([[[[[  1,   2,   3,   4,   5],
          [  6,   7,   8,   9,  10]],

         [[ 11,  12,  13,  14,  15],
          [ 16,  17,  18,  19,  20]]]],



       [[[[ 21,  22,  23,  24,  25],
          [ 26,  27,  28,  29,  30]],

         [[ 31,  32,  33,  34,  35],
          [ 36,  37,  38,  39,  40]]]],



       [[[[ 41,  42,  43,  44,  45],
          [ 46,  47,  48,  49,  50]],

         [[ 51,  52,  53,  54,  55],
          [ 56,  57,  58,  59,  60]]]],



       [[[[ 61,  62,  63,  64,  65],
          [ 66,  67,  68,  69,  70]],

         [[ 71,  72,  73,  74,  75],
          [ 76,  77,  78,  79,  80]]]],



       [[[[ 81,  82,  83,  84,  85],
          [ 86,  87,  88,  89,  90]],

         [[ 91,  92,  93,  94,  95],
          [ 96,  97,  98,  99, 100]]]]])

In [86]:
a4.reshape(-1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# flatten()
* 다차원 배열을 1차원으로 펼쳐줌

In [87]:
a4.ndim

4

In [91]:
a5.ndim

5

In [89]:
a6 = a5.flatten()
print(a6.ndim, a6.shape)
a6

1 (100,)


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# np.flip()
* 행렬의 순서를 뒤집을 때

In [95]:
a4[::-1]

array([[[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]]]])

In [96]:
np.flip(a4)

array([[[[100,  99,  98,  97,  96],
         [ 95,  94,  93,  92,  91]],

        [[ 90,  89,  88,  87,  86],
         [ 85,  84,  83,  82,  81]]],


       [[[ 80,  79,  78,  77,  76],
         [ 75,  74,  73,  72,  71]],

        [[ 70,  69,  68,  67,  66],
         [ 65,  64,  63,  62,  61]]],


       [[[ 60,  59,  58,  57,  56],
         [ 55,  54,  53,  52,  51]],

        [[ 50,  49,  48,  47,  46],
         [ 45,  44,  43,  42,  41]]],


       [[[ 40,  39,  38,  37,  36],
         [ 35,  34,  33,  32,  31]],

        [[ 30,  29,  28,  27,  26],
         [ 25,  24,  23,  22,  21]]],


       [[[ 20,  19,  18,  17,  16],
         [ 15,  14,  13,  12,  11]],

        [[ 10,   9,   8,   7,   6],
         [  5,   4,   3,   2,   1]]]])

# np.linspace(시작, 끝, 구간 수)
* 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때

In [97]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [98]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [99]:
np.linspace(1, 10, 567)

array([ 1.        ,  1.01590106,  1.03180212,  1.04770318,  1.06360424,
        1.0795053 ,  1.09540636,  1.11130742,  1.12720848,  1.14310954,
        1.1590106 ,  1.17491166,  1.19081272,  1.20671378,  1.22261484,
        1.2385159 ,  1.25441696,  1.27031802,  1.28621908,  1.30212014,
        1.3180212 ,  1.33392226,  1.34982332,  1.36572438,  1.38162544,
        1.3975265 ,  1.41342756,  1.42932862,  1.44522968,  1.46113074,
        1.4770318 ,  1.49293286,  1.50883392,  1.52473498,  1.54063604,
        1.5565371 ,  1.57243816,  1.58833922,  1.60424028,  1.62014134,
        1.6360424 ,  1.65194346,  1.66784452,  1.68374558,  1.69964664,
        1.7155477 ,  1.73144876,  1.74734982,  1.76325088,  1.77915194,
        1.795053  ,  1.81095406,  1.82685512,  1.84275618,  1.85865724,
        1.8745583 ,  1.89045936,  1.90636042,  1.92226148,  1.93816254,
        1.9540636 ,  1.96996466,  1.98586572,  2.00176678,  2.01766784,
        2.0335689 ,  2.04946996,  2.06537102,  2.08127208,  2.09

# 정렬과 순위 (sort, argsort)
* np.sort()는 실제로 정렬된 값을 리턴
* np.argsort()는 정렬했을 때의 인덱스 순서를 리턴 (작은수 -> 큰수)
  * 누가 1등인지, 어떤 순서인지 알려줌 
  * 추천시스템, 유사도 비교시 많이 사용됨

In [100]:
f = np.array([5, 7, 11, 1, 3, 2, 54, 0, 0.5, 68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [103]:
# 파이썬의 정렬함수를 사용해도 되지만 결과가 list로 나옴
print(sorted(f), type(sorted(f)))

[np.float64(0.0), np.float64(0.5), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(5.0), np.float64(7.0), np.float64(11.0), np.float64(54.0), np.float64(68.0)] <class 'list'>


* np.sort()

In [105]:
arr = np.array([
    [[5,2,8],
    [1,6,7]],
    [[4,9,3],
    [0,2,1]]
])
print(arr, arr.shape)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]] (2, 2, 3)


In [106]:
# np.sort의 기본 정렬: 가장 안쪽 차원 1차원 배열을 정렬
# axis = -1 (기본값)
print(arr)
np.sort(arr)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[2, 5, 8],
        [1, 6, 7]],

       [[3, 4, 9],
        [0, 1, 2]]])

In [107]:
# axis=1 2차원 배열에서 각 열을 정렬
print(arr)
np.sort(arr, axis=1)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[1, 2, 7],
        [5, 6, 8]],

       [[0, 2, 1],
        [4, 9, 3]]])

In [108]:
# axis = 0 2차원 배열에서 같은 행의 요소끼리 정렬
print(arr)
np.sort(arr, axis=0)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[4, 2, 3],
        [0, 2, 1]],

       [[5, 9, 8],
        [1, 6, 7]]])

# argsort()
* 자료중 값을 작은 것에서 큰 순으로 **원래 인덱스** 출력

In [116]:
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [117]:
s = g.argsort()
print(s)  # [2, 5, 1, 0, 4, 3]
# [-7, 0, 0.5, 5, 10, 42]

[2 5 1 0 4 3]


In [121]:
g[[2, 5, 1, 0, 4, 3]]

array([-7. ,  0. ,  0.5,  5. , 10. , 42. ])

In [127]:
g[[2, 5, 1, 4, 3]][::-1]

array([42. , 10. ,  0.5,  0. , -7. ])

# 최대값, 최솟값 위치 찾기 (argmax / argmin)

In [128]:
price = np.array([101, 105, 103, 120, 119])
price

array([101, 105, 103, 120, 119])

In [130]:
max_position = np.argmax(price)
print("최고가 index: ", max_position, "값: ", price[max_position])

최고가 index:  3 값:  120


In [131]:
min_position = np.argmin(price)
print("최저가 index: ", min_position, "값: ", price[min_position])

최저가 index:  0 값:  101


# np.where(조건, 참, 거짓) 3항 연산 

In [132]:
nums = np.arange(1, 11)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
result = []
for num in nums:
    if num % 2 == 0:
        result.append("짝수")
    else:
        result.append("홀수")
result

['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수']

In [136]:
result2 = ["짝수" if num % 2 == 0 else "홀수" for num in nums]
result2

['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수']

In [137]:
result3 = np.where(nums % 2 == 0, "짝수", "홀수")
result3

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

# 배열 합치기 np.concatenate()

In [138]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a, a.ndim, a.shape)
print(b, b.ndim, b.shape)

[[1 2]
 [3 4]] 2 (2, 2)
[[5 6]
 [7 8]] 2 (2, 2)


* np.concatenate((a, b), axis=0/1) 기본값은 axis=0
* axis=0 아래로 합쳐짐, 행이 늘어남
* axis=1 옆으로 합쳐짐, 열이 늘어남

In [139]:
# axis=0 아래로 늘어나면서 합쳐짐
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [140]:
# axis=1 옆으로 늘어나면서 합쳐짐
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [141]:
c = np.array([5,6])
c

array([5, 6])

In [143]:
print(c, c.ndim, c.shape)

[5 6] 1 (2,)


In [144]:
np.concatenate((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [145]:
np.concatenate((a,[c]))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
np.concatenate((a,[c]), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [152]:
d = np.array([7,8,9], axis=1)
print(d, d.ndim, d.shape)

TypeError: array() got an unexpected keyword argument 'axis'

In [149]:
print(a, a.ndim, a.shape)

[[1 2]
 [3 4]] 2 (2, 2)


In [151]:
np.concatenate((a, [d]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

* 전치행렬
* 행과 열이 뒤바뀐 행렬
* transpose, T

In [156]:
c2 = np.array([[5,6]])
print(c2, c2.ndim, c2.shape)

[[5 6]] 2 (1, 2)


In [157]:
np.concatenate((a, c2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
print(a.shape, c2.shape)

(2, 2) (1, 2)


In [158]:
np.concatenate((a, c2), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [161]:
print(c2.T, c2.T.ndim, c2.T.shape)

[[5]
 [6]] 2 (2, 1)


In [163]:
print(a.shape, c2.T.shape)

(2, 2) (2, 1)


In [164]:
np.concatenate((a, c2.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [165]:
c2.transpose()

array([[5],
       [6]])

In [166]:
c2

array([[5, 6]])

# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스(2D)와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰주는것

In [167]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [168]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [169]:
b = np.array([10, 20, 30, 40, 50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [172]:
c = np.array([10, 20, 30, 40])
print(c, c.ndim, c.shape)

[10 20 30 40] 1 (4,)


In [171]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [170]:
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])

In [173]:
a+ c

ValueError: operands could not be broadcast together with shapes (3,5) (4,) 

In [178]:
x = np.array([1,2,3])
y = np.array([10,20,30])

In [179]:
x + y

array([11, 22, 33])

# 축(axis) 기반 집계 연산 np.sum()
* axis=0 세로(열) 단위 연산
* axis=1 가로(행) 단위 연산

In [180]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat, mat.ndim, mat.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [185]:
print("전체 요소의 합: ", np.sum(mat))
print("열별 합(axis=0): ", np.sum(mat, axis=0))
print("행별 합(axis=1): ", np.sum(mat, axis=1))

전체 요소의 합:  21
열별 합(axis=0):  [5 7 9]
행별 합(axis=1):  [ 6 15]


# np.mean() 평균

In [186]:
print("전체 요소의 평균: ", np.mean(mat))
print("열별 평균(axis=0): ", np.mean(mat, axis=0))
print("행별 평균(axis=1): ", np.mean(mat, axis=1))

전체 요소의 평균:  3.5
열별 평균(axis=0):  [2.5 3.5 4.5]
행별 평균(axis=1):  [2. 5.]


# 누적합/ 누적곱 (cumsum/cumprod)
* comsum: 앞에서부터 계속 더한 결과(현금 잔고 추이 등)
* comprod: 앞에서부터 계속 곱한 결과(누적 성장률)

In [188]:
cashflow = np.array([100, -20, 50, -10])
print("현금흐름: ", cashflow)
print("누적잔고: ", np.cumsum(cashflow))

현금흐름:  [100 -20  50 -10]
누적잔고:  [100  80 130 120]


In [189]:
# 매년 매출 성장 비율
rates = np.array([10.5, 13, 0.5, 1.3])
print("연별 성장률: ", rates)
print("누적 성장률: ", np.cumprod(rates))

연별 성장률:  [10.5 13.   0.5  1.3]
누적 성장률:  [ 10.5   136.5    68.25   88.725]


# 분산(var), 표준편차(std)

In [190]:
classA = np.array([70, 72, 68, 69, 71])
classB = np.array([50, 90, 30, 100, 10])

In [191]:
print("A반 평균: ", np.mean(classA))
print("B반 평균: ", np.mean(classB))

A반 평균:  70.0
B반 평균:  56.0


In [192]:
print("A반 표준편차: ", np.std(classA))
print("B반 표준편차: ", np.std(classB))

A반 표준편차:  1.4142135623730951
B반 표준편차:  34.40930106817051


In [193]:
print("A반 분산: ", np.var(classA))
print("B반 분산: ", np.var(classB))

A반 분산:  2.0
B반 분산:  1184.0


# 고유값과 등장 빈도(unique)

In [196]:
brands = np.array(['AAPL', "TSLA", "AAPL", "NVDA", "TSLA", "GOOGL"])

In [197]:
np.unique(brands)

array(['AAPL', 'GOOGL', 'NVDA', 'TSLA'], dtype='<U5')

In [198]:
uniq, cnt = np.unique(brands, return_counts=True)
print("고유 브랜드: ", uniq)
print("각 브랜드 등장 횟수: ", cnt)

고유 브랜드:  ['AAPL' 'GOOGL' 'NVDA' 'TSLA']
각 브랜드 등장 횟수:  [2 1 1 2]
